In [60]:
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import os

In [11]:
dF = pd.read_json('data/beer_fixed.json',lines=True)

In [61]:
dF.keys()

Index(['review/appearance', 'beer/style', 'review/palate', 'review/taste',
       'beer/name', 'review/timeUnix', 'beer/ABV', 'beer/beerId',
       'beer/brewerId', 'review/timeStruct', 'review/overall', 'review/text',
       'user/profileName', 'review/aroma', 'user/gender', 'user/birthdayRaw',
       'user/birthdayUnix', 'user/ageInSeconds'],
      dtype='object')

In [62]:
dF.head()

,review/appearance,beer/style,review/palate,review/taste,beer/name,review/timeUnix,beer/ABV,beer/beerId,beer/brewerId,review/timeStruct,review/overall,review/text,user/profileName,review/aroma,user/gender,user/birthdayRaw,user/birthdayUnix,user/ageInSeconds
0,2.5,Hefeweizen,1.5,1.5,Sausa Weizen,1234817823,5.0,47986,10325,"{'isdst': 0, 'mday': 16, 'hour': 20, 'min': 57...",1.5,A lot of foam. But a lot.\tIn the smell some b...,stcules,2.0,NaN,NaN,NaN,NaN
1,3.0,English Strong Ale,3.0,3.0,Red Moon,1235915097,6.2,48213,10325,"{'isdst': 0, 'mday': 1, 'hour': 13, 'min': 44,...",3.0,"Dark red color, light beige foam, average.\tIn...",stcules,2.5,NaN,NaN,NaN,NaN
2,3.0,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,1235916604,6.5,48215,10325,"{'isdst': 0, 'mday': 1, 'hour': 14, 'min': 10,...",3.0,"Almost totally black. Beige foam, quite compac...",stcules,2.5,NaN,NaN,NaN,NaN
3,3.5,German Pilsener,2.5,3.0,Sausa Pils,1234725145,5.0,47969,10325,"{'isdst': 0, 'mday': 15, 'hour': 19, 'min': 12...",3.0,"Golden yellow color. White, compact foam, quit...",stcules,3.0,NaN,NaN,NaN,NaN
4,4.0,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,1293735206,7.7,64883,1075,"{'isdst': 0, 'mday': 30, 'hour': 18, 'min': 53...",4.0,"According to the website, the style for the Ca...",johnmichaelsen,4.5,Male,"Jun 16, 1901",-2.163082e+09,3.581417e+09

In [63]:
dF.count()

review/appearance    1586614
beer/style           1586614
review/palate        1586614
review/taste         1586614
beer/name            1586614
review/timeUnix      1586614
beer/ABV             1518829
beer/beerId          1586614
beer/brewerId        1586614
review/timeStruct    1586614
review/overall       1586614
review/text          1586614
user/profileName     1586614
review/aroma         1586614
user/gender           637221
user/birthdayRaw      327596
user/birthdayUnix     327596
user/ageInSeconds     327596
dtype: int64

In [64]:
print('Number of reviewers: %d'%len(dF['user/profileName'].unique()))

Number of reviewers: 33388

In [65]:
tempDF = dF.head()

In [66]:
dF.loc[dF['beer/style'] == "Hefeweizen"][['beer/style','review/appearance','review/palate','review/taste','review/overall','review/aroma']]

,beer/style,review/appearance,review/palate,review/taste,review/overall,review/aroma
0,Hefeweizen,2.5,1.5,1.5,1.5,2.0
1672,Hefeweizen,3.0,4.0,4.5,4.0,3.5
1843,Hefeweizen,3.0,3.0,3.5,3.5,3.5
1844,Hefeweizen,3.5,3.5,3.5,4.0,4.0
1845,Hefeweizen,4.0,3.5,4.0,3.5,4.0
...,...,...,...,...,...,...
1585478,Hefeweizen,3.5,4.0,2.5,3.0,4.0
1586140,Hefeweizen,2.0,1.5,3.0,2.5,2.5
1586141,Hefeweizen,3.5,3.5,3.5,4.0,3.5
1586142,Hefeweizen,3.0,2.0,1.5,1.5,2.0
1586595,Hefeweizen,4.0,4.0,4.0,4.0,3.5

In [67]:
reviewTags = ['review/appearance','review/palate','review/taste','review/overall','review/aroma']
figsize = (12,12)

if not(os.path.isdir('images')):
    os.mkdir('images')
    
    
for beerStyle in dF['beer/style'].unique():
    beerStyleText = beerStyle.replace(' /','')
    print(beerStyleText)
    pandas.plotting.scatter_matrix(dF.loc[dF['beer/style'] == beerStyle][['beer/style','review/appearance','review/palate','review/taste','review/overall','review/aroma']],figsize=figsize)
    plt.suptitle(beerStyleText)
    plt.savefig('images/%s.jpg'%beerStyleText)
    plt.close()